# 数据库配置信息(选填，存储历史对话用)
mysql:
 host: 'localhost'
 port: 3306
 user: 'root'
 password: 'WangHan@520'
 database: 'client'

# 服务器配置(必填)
server:
 host: "localhost"
 port: 1111
   #location: "https://chatpua.cpolar.top"
 location: "http://localhost:1111"
