mysql:
 host: 'localhost'
 port: 3306
 user: 'root'
 password: '114514'
 database: 'client'

# 服务器配置(必填)
server:
 host: "localhost"
 port: 1145
 location: "https://example.com"  #本机访问改成"http://loaclhost:1145"